---
abstract: 'Copy secrets from a YAML/JSON cipherstore into the clipboard (pbcopy, xsel, xclip)'
author:
  - 'Robert Krimen <robertkrimen@gmail.com>'
build_requires:
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-locket
requires:
  Any::Moose: 0
  File::HomeDir: 0
  Getopt::Usaginator: 0
  JSON: 0
  Path::Class: 0
  String::Util: 0
  Term::EditorEdit: 0
  Term::ReadKey: 0
  Try::Tiny: 0
  YAML::XS: 0
version: 0.0013
